name: docxtpl
description: a word document template plugin to easily populate and generate word documents from templates
version: 0.1.0
author: Donald Chinhuru<donnclab@gmail.com>
homepage: https://github.com/DonnC/docxtpl

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  http:
  archive:
  xml:
  path:

dev_dependencies:
  lints: ^1.0.0