name: docxtpl
description: a word document template plugin to easily populate and generate word documents from templates
version: 0.0.1
author: Donald Chinhuru<donnclab@gmail.com>
homepage: https://github.com/DonnC/docxtpl

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  archive: ^3.3.5
  xml: ^6.1.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: