name: docxtpl
description: a word document template plugin to easily populate and generate word documents from templates
version: 0.0.1
homepage: https://github.com/DonnC/docxtpl
funding:
  - https://www.paypal.me/donnclab

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  xml: ^6.5.0

dev_dependencies:
  test: ^1.25.8
